# Generated by Django 4.0.4 on 2022-05-09 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_desc',
            field=models.TextField(blank=True),
        ),
    ]
