# Generated by Django 4.0.4 on 2022-05-09 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_room_room_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
