# Generated by Django 4.0.4 on 2022-06-01 13:53

from django.db import migrations, models
import room.models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_alter_room_owner_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_name',
            field=models.CharField(max_length=256, unique=True, validators=[room.models.validate_room_name]),
        ),
    ]
